### ISSUE TITLE
CER Component addition

### ISSUE THREAD

**Issue by aakash1104** [amyjko/faculty#122]
Hi, I see that you have a cer.js as well as a separate github gist `cer.md`. From what I can tell, the JS component doesn't seem to use/import the gist? I do have a few faculty additions I'd like to submit. I don't think I can submit a pull request for Github Gists. Could I make a pull request by updating the `cer.js` file? This probably won't update the github gist you maintain.

**Comment by amyjko** [comment]
Hello Aakash! Thanks for catching this; I migrated the Gist content to my faculty web page recently (Gists are kind of limited). I need to delegate the Gist. Submitting a pull request on `cer.js` works for me!

**Comment by aakash1104** [comment]
Hi hi hi! :) Just submitted a PR (https://github.com/amyjko/faculty/pull/123) for this.

Have you considered using something like AirTable to maintain a list of faculty who do research in CER? That way you can even add filters easily to search for faculty and also embed this on webpages!

Cheers!

**Comment by amyjko** [comment]
Thank you! Comments on the PR.

I haven't thought about using AirTable (I have so little time to work on this site), but it's a good idea. Feel free to file an issue if you like.

**Comment by aakash1104** [comment]
I'll create another issue and find some AirTable resources. I found another repo that I reference often that uses AirTable. I'll try to find something concrete and create an issue. But you can go ahead and close this issue.

**Comment by amyjko** [comment]
Thanks!
