### ISSUE TITLE
preferred citation / acknowledge for adapting website?

### ISSUE THREAD

**Issue by kyleniemeyer** [amyjko/faculty#173]
Hi @amyjko! Your new website is fantastic, and I would love to adapt the infrastructure you've developed for my own lab website. (I'm currently dealing with a hard-to-maintain Frankenstein's monster of Jekyll and bootstrap.) 

Before I do so I wanted to ask:

1. First, are you ok with this? Obviously the content would be different but there would be clear similarities too, in terms of layout.
2. If you are, do you have a preferred acknowledgment/"citation" to your site? I saw the CC0 license, but I think it would still be appropriate to point to you/here as the original source and inspiration.

Thanks!

**Comment by amyjko** [comment]
Go for it! I really do mean the `CC0`; consider it public domain. Just mentioning me by name and pointing to `amyjko.com` or the repo would be great. I can't wait to see what you do with it.

Note: one motivation for the CC0 is sort of an implied lack of support: I'm definitely not writing or maintaining this in a form suitable for reuse, so a fork is probably a smart move :)

**Comment by kyleniemeyer** [comment]
Understood, and thanks! I'll definitely share my version when it's ready. 

I'm just playing around with it right now, but forking it is a good idea (though might need to delete my current website repo and start anew, since *that* one is also a fork...)
