### ISSUE TITLE
New question about lablets.

### ISSUE THREAD

**Issue by SMSadegh19** [amyjko/faculty#175]
Hi!
I've read the description about lablets. The information is only for Washington university students.
Can any student have an opportunity to participate in lablets?
What should they do if they want to participate?

**Comment by amyjko** [comment]
Lablets are only for students enrolled at the University of Washington. (I barely have capacity to meet demand for UW, let alone the whole world — it's intensive mentoring work).

**Comment by SMSadegh19** [comment]
Thanks.
Do you think it would be helpful to include that information on the page? (As a FAQ item)
I think other people who might be in a similar situation as me might find it confusing otherwise.
