### ISSUE TITLE
Fix broken URL of the Big Book 

### ISSUE THREAD

**Issue by yiji-zhang-rhit** [amyjko/faculty#184]
**Issue:** The [current URL](https://helloworld.raspberrypi.org/issues/0?fbclid=IwAR3D6RFiGvTno6VgMiMnGRXq7vJHVaIThyXH5mnB_-rYWjiPSyoiJDSyJxc) leads to "The page you were looking for doesn't exist".

**Consider this url:** https://helloworld.raspberrypi.org/books/big_book_of_pedagog

(It seems like they changed the use of dash to underscore in the book name.)

**Comment by amyjko** [comment]
Thanks for reporting! This fix should be live now.
