### ISSUE TITLE
Update Shallow End and Clubhouse links

### ISSUE THREAD

**Issue by azmec** [amyjko/faculty#203]
**Issue**: [Current link](https://mitpress.mit.edu/books/stuck-shallow-end) to _Stuck in the Shallow End_ and [current link](https://mitpress.mit.edu/9780262332453/) to _Unlocking the Clubhouse: Women in Computing_ leads to a "Book not found..." page.

- Working link to _Shallow End_: https://mitpress.mit.edu/9780262514040/stuck-in-the-shallow-end/
- Working link to _Unlocking the Clubhouse_: https://mitpress.mit.edu/9780262632690/unlocking-the-clubhouse/

**Comment by amyjko** [comment]
Fixed, thanks for reporting.
