### ISSUE TITLE
email is one click away?

### ISSUE THREAD

**Issue by iceLearn** [amyjko/faculty#51]
One thing I observed is when clicking contact for email - its further expect to click to get email 				
					`link="mailto:ajko@uw.edu"`

I know if someone really wants to find your email - then the idea is to click, I usually block new tab/popup in my browser, so it makes bit harder. You must be having a strong reason for it, but if not, pls consider to display straight under the header  down 
`<br/><strong><a href="https://twitter.com/search?q=%23BlackLivesMatter">#BlackLivesMatter</a></strong>`
		
P.S We support you and love all of your work towards diversity and educating the general.

**Comment by amyjko** [comment]
Thanks for the feedback! Indeed, I obscure my email to reduce the amount of email I get (I usually have 150+ to respond to a day). But perhaps it's a little _too_ obscure :)
